### ISSUE TITLE
bytes2uint vs cast and to_int ?

### ISSUE THREAD

**Issue by awelzel** [keithjjones/zeek-njrat-detector#2]
Is bytes2uint the same as [to_int()](https://docs.zeek.org/projects/spicy/en/latest/programming/language/types.html#method-bytes::to_int) with a cast and could possibly reuse that code?

https://github.com/keithjjones/zeek-njrat-detector/blob/2fd88375f03233884229d269406d183adc83b7ab/analyzer/njrat.spicy#L3C1-L4C1

**Comment by keithjjones** [comment]
It is!  I missed that!  I just swapped it out and cut v0.1.6.  Thanks!
